"""initial core schema

Creates the core PostgreSQL/TimescaleDB tables from the models metadata.
After running this, apply sql/002_hypertables.sql to convert `bars` to a hypertable.

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-01
"""
from __future__ import annotations

from alembic import op

from astroquant.db.models import Base

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Bootstrap migration: create all core tables from the declarative metadata.
    # Subsequent schema changes should use autogenerated migrations (alembic revision --autogenerate).
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
